name: SwiftFormat

on: 
  workflow_dispatch: {}
  pull_request_review:
    types: [submitted]

jobs:
  format:
    if: github.event.review.state == 'approved' || github.event_name != 'pull_request_review'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}

      - name: Install SwiftFormat
        uses: Cyberbeni/install-swift-tool@v2
        with:
          url: https://github.com/nicklockwood/SwiftFormat

      - name: Format files
        run: swiftformat --indent 4 .

      - name: Commit formatted files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: SwiftFormat
