name: InstallSwiftFormat

on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch: {}

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Install SwiftFormat
        uses: Cyberbeni/install-swift-tool@v2
        with:
          url: https://github.com/nicklockwood/SwiftFormat
